//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUAHANG_BAN_SANPHAM
    {
        public string MACH { get; set; }
        public string MASP { get; set; }
    
        public virtual CUAHANG CUAHANG { get; set; }
        public virtual CUAHANG CUAHANG1 { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual SANPHAM SANPHAM1 { get; set; }
    }
}
