set dateformat dmy

CREATE DATABASE QuanLyBanHangNovea

USE QuanLyBanHangNovea
---------------------
CREATE TABLE KHACH
(
	MAKH varchar(128) primary key,
	TAIKHOAN varchar(max),
	MATKHAU varchar(max),
	HOTEN nvarchar(max),
	NGSINH datetime,
	GIOITINH nvarchar(3),
	SDT varchar(15),
	EMAIL varchar(max),
	DIACHI nvarchar(max),
	NGDK datetime,
	DOANHSO money,
	AVATAR varbinary(max)
)

CREATE TABLE CUAHANG
(
	MACH varchar(128) primary key,
	TAIKHOAN varchar(max),
	MATKHAU varchar(max),
	TENCH nvarchar(max),
	DIADIEM nvarchar(max),
	SDT varchar(15),
	EMAIL varchar(max),
	NGDK datetime,	
	DOANHTHU money,
	AVATAR varbinary(max)	
)

CREATE TABLE SANPHAM
(
	MASP varchar(128) primary key,
	TENSP nvarchar(max),
	LOAISP nvarchar(max),
	DONVI nvarchar(max),
	DONGIA money,
	SIZE varchar(10),
	MOTA nvarchar(max),
	AVAILABLE bit,
	HINHSP varbinary(max),
	MACH varchar(128) FOREIGN KEY REFERENCES CUAHANG(MACH)
)

CREATE TABLE HOADON
(
	SOHD varchar(128) primary key,
	NGMH datetime,
	TONGTIEN money,
	DONE bit,
	MAKH varchar(128) FOREIGN KEY REFERENCES KHACH(MAKH),
	MACH varchar(128) FOREIGN KEY REFERENCES CUAHANG(MACH),
)

CREATE TABLE CTHD
(
	SOHD varchar(128) FOREIGN KEY REFERENCES HOADON(SOHD),
	MASP varchar(128) FOREIGN KEY REFERENCES SANPHAM(MASP),
		CONSTRAINT PK_CTHD PRIMARY KEY (SOHD,MASP),
	SOLUONG int,
	TRIGIA money,
	LuongDa varchar(10),
	LuongDuong varchar(10)
)

-----------
-----------
INSERT INTO KHACH(MAKH,TAIKHOAN ,MATKHAU,HOTEN,NGSINH,GIOITINH,SDT,EMAIL,DIACHI,AVATAR, DOANHSO, NGDK) VALUES 
	('KH01','q','q',N'Tuấn Kiệt', '20/03/2010','Nam','123','1@gm.uit.edu.vn','q','string/a/b', 0,'22/01/2010')
-----------
-----------
INSERT INTO CUAHANG(MACH,TAIKHOAN ,MATKHAU,TENCH,SDT,EMAIL,DIADIEM,AVATAR, DOANHTHU, NGDK) VALUES 
	('CH01','q','q',N'Hai Lần Cà phê','1234','2@gm.uit.edu.vn','q','string/a/b', 0,'10/08/2022')
-----------
-----------
INSERT INTO SANPHAM(MASP,TENSP,LOAISP,DONVI,DONGIA,SIZE,MOTA,AVAILABLE,HINHSP,MACH) VALUES 
('SP01',N'Trà sữa tình yêu',N'trà sữa','ly','45000','M',N'Thơm ngon mời bạn măm nha','true','a/b/c','CH01')
INSERT INTO SANPHAM(MASP,TENSP,LOAISP,DONVI,DONGIA,SIZE,MOTA,AVAILABLE,HINHSP,MACH) VALUES 
('SP02',N'Trà sữa uyên ương',N'trà sữa','ly','40000','M',N'Thơm ngon mời bạn măm nha','true','a/b/c','CH01')
-----------
-----------
INSERT INTO HOADON(SOHD,NGMH,DONE,MAKH,MACH, TONGTIEN) VALUES('HD01','20/01/2023','true','KH01','CH01', 0)
-----------
-----------
INSERT INTO CTHD(SOHD, MASP, SOLUONG, LUONGDA,LUONGDUONG, TRIGIA) VALUES ('HD01','SP01',5,'50','50', 0)
INSERT INTO CTHD(SOHD, MASP, SOLUONG, LUONGDA,LUONGDUONG, TRIGIA) VALUES ('HD01','SP02',5,'50','50', 0)
-----------
-----------

/*--I.Rang buoc toan ven cho KHACH--*/
--1.Doanh so ban ra cho 1 khach hang bang tong tat ca tong tien trong hoa don ma khach hang do mua
	--a.Trigger cho bang KHACH--
		---INSERT---
CREATE TRIGGER TRG_KHACH_DOANHSO_INSERT
ON KHACH
AFTER INSERT
AS
BEGIN
	DECLARE @MAKH varchar(128)

	SELECT @MAKH = MAKH
	FROM  inserted

	UPDATE KHACH
	SET  DOANHSO = 0
	WHERE MAKH = @MAKH
END
		---UPDATE---
CREATE TRIGGER TRG_KHACH_DOANHSO_UPDATE
ON KHACH
AFTER UPDATE
AS IF(UPDATE(DOANHSO))
BEGIN
	DECLARE @MAKH varchar(128)
	DECLARE @DOANHSO money
	DECLARE @TONGDS money
	
	SET @TONGDS = 0
	
	SELECT @MAKH = MAKH, @DOANHSO = DOANHSO 
	FROM inserted

	SELECT @TONGDS = SUM(TONGTIEN) 
	FROM HOADON
	WHERE MAKH = @MAKH
	GROUP BY MAKH

	IF(@DOANHSO <> @TONGDS)
	BEGIN
		ROLLBACK TRANSACTION
	END
END
	--b.Trigger cho bang HOADON--
		---INSERT, DELETE---
CREATE TRIGGER TRG_HOADON_DOANHSO_INSERT_DELETE
ON HOADON
AFTER INSERT, DELETE
AS 
BEGIN
	DECLARE @MAKH varchar(128)
	DECLARE @TONGDSTHEM money
	DECLARE @TONGDSTRU money

	SET @TONGDSTHEM = 0
	SET @TONGDSTRU = 0

	SELECT @TONGDSTHEM = TONGTIEN, @MAKH = MAKH 
	FROM inserted

	SELECT @TONGDSTRU = TONGTIEN, @MAKH = MAKH 
	FROM deleted

	UPDATE KHACH
	SET DOANHSO = DOANHSO + @TONGDSTHEM - @TONGDSTRU
	WHERE MAKH = @MAKH
END
		---UPDATE---
CREATE TRIGGER TRG_HOADON_DOANHSO_UPDATE
ON HOADON
AFTER UPDATE
AS IF(UPDATE(TONGTIEN) OR UPDATE(MAKH))
BEGIN
	DECLARE @MAKH varchar(128)
	DECLARE @TONGDSTHEM money
	DECLARE @TONGDSTRU money

	SET @TONGDSTHEM = 0
	SET @TONGDSTRU = 0

	SELECT @TONGDSTHEM = TONGTIEN, @MAKH = MAKH 
	FROM inserted

	SELECT @TONGDSTRU = TONGTIEN, @MAKH = MAKH 
	FROM deleted

	UPDATE KHACH
	SET DOANHSO = DOANHSO + @TONGDSTHEM - @TONGDSTRU
	WHERE MAKH = @MAKH
END

/*--II.Rang buoc toan ven cho HOADON--*/
--1.Tong tien bang tong tri gia cac chi tiet hoa don
	--a.Trigger cho bang HOADON--
		---INSERT---
CREATE TRIGGER TRG_HOADON_TONGTIEN_INSERT
ON HOADON
AFTER INSERT
AS
BEGIN
	DECLARE @SOHD varchar(128)

	SELECT @SOHD = SOHD
	FROM  inserted

	UPDATE HOADON
	SET  TONGTIEN = 0
	WHERE SOHD = @SOHD
END
		---UPDATE---
CREATE TRIGGER TRG_HOADON_TONGTIEN_UPDATE
ON HOADON
AFTER UPDATE
AS IF(UPDATE(TONGTIEN))
BEGIN
	DECLARE @SOHD varchar(128)
	DECLARE @TONGTIEN money
	DECLARE @TONGTRIGIA money
	
	SET @TONGTRIGIA = 0
	
	SELECT @SOHD = SOHD, @TONGTIEN = TONGTIEN 
	FROM inserted

	SELECT @TONGTRIGIA = SUM(TRIGIA) 
	FROM CTHD
	WHERE SOHD = @SOHD
	GROUP BY SOHD

	IF(@TONGTIEN <> @TONGTRIGIA)
	BEGIN
		ROLLBACK TRANSACTION
	END
END
	--b.Trigger cho bang CTHD--
		---INSERT, DELETE, UPDATE---
CREATE TRIGGER TRG_CTHD_TONGTIEN_INSERT_DELETE_UPDATE
ON CTHD
AFTER INSERT, DELETE, UPDATE
AS 
BEGIN
	DECLARE @SOHD varchar(128)
	DECLARE @TONGTRIGIATHEM money
	DECLARE @TONGTRIGIATRU money

	SET @TONGTRIGIATHEM = 0
	SET @TONGTRIGIATRU = 0

	SELECT @TONGTRIGIATHEM = TRIGIA, @SOHD = SOHD 
	FROM inserted

	SELECT @TONGTRIGIATRU = TRIGIA, @SOHD = SOHD 
	FROM deleted

	UPDATE HOADON
	SET TONGTIEN = TONGTIEN + @TONGTRIGIATHEM - @TONGTRIGIATRU
	WHERE SOHD = @SOHD
END

/*--III.Rang buoc toan ven cho CTHD--*/
--1.Tri gia bang so luong nhan don gia
	--Trigger cho bang CTHD--
		---INSERT---
CREATE TRIGGER TRG_CTHD_TRIGIA_INSERT
ON CTHD
AFTER INSERT
AS
BEGIN
	DECLARE @MASP varchar(128)
	DECLARE @SOHD varchar(128)
	DECLARE @SOLUONG int
	DECLARE @DONGIA money

	SELECT @MASP = inserted.MASP, @SOHD = inserted.SOHD, @SOLUONG = inserted.SOLUONG, @DONGIA = SANPHAM.DONGIA
	FROM inserted, SANPHAM
	WHERE inserted.MASP = SANPHAM.MASP
	
	UPDATE CTHD
	SET TRIGIA = @SOLUONG * @DONGIA
	WHERE MASP = @MASP AND SOHD = @SOHD
END
		---UPDATE_SOLUONG---
CREATE TRIGGER TRG_CTHD_TRIGIA_UPDATE_SOLUONG
ON CTHD
AFTER UPDATE
AS IF (UPDATE(SOLUONG))
BEGIN
	DECLARE @MASP varchar(128)
	DECLARE @SOHD varchar(128)
	DECLARE @SOLUONG int
	DECLARE @DONGIA money

	SELECT @MASP = inserted.MASP, @SOHD = inserted.SOHD, @SOLUONG = inserted.SOLUONG, @DONGIA = SANPHAM.DONGIA
	FROM inserted, SANPHAM
	WHERE inserted.MASP = SANPHAM.MASP

	UPDATE CTHD
	SET TRIGIA = @SOLUONG * @DONGIA
	WHERE MASP = @MASP AND SOHD = @SOHD
END
		---UPDATE_TRIGIA---
CREATE TRIGGER TRG_CTHD_TRIGIA_UPDATE_TRIGIA
ON CTHD
AFTER UPDATE
AS IF (UPDATE(TRIGIA))
BEGIN
	DECLARE @MASP varchar(128)
	DECLARE @SOHD varchar(128)
	DECLARE @SOLUONG int
	DECLARE @TRIGIA money
	DECLARE @DONGIA money

	SELECT @MASP = inserted.MASP, @SOHD = inserted.SOHD, @TRIGIA = inserted.TRIGIA, @SOLUONG = inserted.SOLUONG, @DONGIA = SANPHAM.DONGIA
	FROM inserted, SANPHAM
	WHERE inserted.MASP = SANPHAM.MASP

	IF( @TRIGIA <> (@SOLUONG * @DONGIA) )
	BEGIN
		ROLLBACK TRANSACTION
	END
END
	--Trigger cho bang SANPHAM--
		---UPDATE---
CREATE TRIGGER TRG_SANPHAM_TRIGIA_UPDATE
ON SANPHAM
AFTER UPDATE
AS IF(UPDATE(DONGIA))
BEGIN
	DECLARE @MASP varchar(128)
	DECLARE @SOHD varchar(128)
	DECLARE @SOLUONG int
	DECLARE @DONGIA money

	SELECT @MASP = inserted.MASP, @SOHD = CTHD.SOHD, @SOLUONG = CTHD.SOLUONG, @DONGIA = inserted.DONGIA
	FROM inserted, CTHD
	WHERE inserted.MASP = CTHD.MASP

	UPDATE CTHD
	SET TRIGIA = @SOLUONG * @DONGIA
	WHERE MASP = @MASP AND SOHD = @SOHD
END

/*--IV.Rang buoc toan ven cho CUAHANG--*/
--1.Doanh thu 1 cua hang bang tong tat ca tong tien xuat tu cua hang do
	--Trigger cho bang CUAHANG--
		---INSERT---
CREATE TRIGGER TRG_CUAHANG_DOANHTHU_INSERT
ON CUAHANG
AFTER INSERT
AS 
BEGIN
	DECLARE @MACH varchar(128)

	SELECT @MACH = inserted.MACH
	FROM inserted

	UPDATE CUAHANG
	SET DOANHTHU = 0
	WHERE MACH = @MACH
END
		---UPDATE---
CREATE TRIGGER TRG_CUAHANG_DOANHTHU_UPDATE
ON CUAHANG
AFTER UPDATE
AS IF(UPDATE(DOANHTHU))
BEGIN
	DECLARE @MACH varchar(128)
	DECLARE @DOANHTHU money
	DECLARE @TONGcuaTONGTIEN money

	SET @TONGcuaTONGTIEN = 0

	SELECT @MACH = MACH, @DOANHTHU = DOANHTHU
	FROM inserted

	SELECT @TONGcuaTONGTIEN = SUM(HOADON.TONGTIEN)
	FROM inserted, HOADON
	WHERE inserted.MACH = HOADON.MACH
	GROUP BY inserted.MACH 

	IF(@DOANHTHU <> @TONGcuaTONGTIEN)
	BEGIN
		ROLLBACK TRANSACTION
	END
END
	--Trigger cho bang HOADON--
		---INSERT, DELETE---
CREATE TRIGGER TRG_HOADON_DOANHTHU_INSERT_DELETE
ON HOADON
AFTER INSERT, DELETE
AS 
BEGIN
	DECLARE @MACH varchar(128)
	DECLARE @TONGDOANHTHUTHEM money
	DECLARE @TONGDOANHTHUTRU money

	SET @TONGDOANHTHUTHEM = 0
	SET @TONGDOANHTHUTRU = 0

	SELECT @MACH = inserted.MACH, @TONGDOANHTHUTHEM = inserted.TONGTIEN
	FROM inserted

	SELECT @MACH = deleted.MACH, @TONGDOANHTHUTRU = deleted.TONGTIEN
	FROM deleted

	UPDATE CUAHANG
	SET DOANHTHU = DOANHTHU + @TONGDOANHTHUTHEM - @TONGDOANHTHUTRU
	WHERE MACH = @MACH
END
		---UPDATE---
CREATE TRIGGER TRG_HOADON_DOANHTHU_UPDATE
ON HOADON
AFTER UPDATE
AS IF(UPDATE(MACH) OR UPDATE(TONGTIEN))
BEGIN
	DECLARE @MACH varchar(128)
	DECLARE @TONGDOANHTHUTHEM money
	DECLARE @TONGDOANHTHUTRU money

	SET @TONGDOANHTHUTHEM = 0
	SET @TONGDOANHTHUTRU = 0

	SELECT @MACH = inserted.MACH, @TONGDOANHTHUTHEM = inserted.TONGTIEN
	FROM inserted

	SELECT @MACH = deleted.MACH, @TONGDOANHTHUTRU = deleted.TONGTIEN
	FROM deleted

	UPDATE CUAHANG
	SET DOANHTHU = DOANHTHU + @TONGDOANHTHUTHEM - @TONGDOANHTHUTRU
	WHERE MACH = @MACH
END
